import type {Metadata} from 'next';
import RootLayoutComponent from '@/core/layouts/root/root.layout';
import nunito from '@/assets/fonts/Nunito';
import classNames from 'classnames';
import '@/assets/styles/style.scss';
import {Params} from 'next/dist/shared/lib/router/utils/route-matcher';
import TranslationProvider from '@/i18n/transaltion-provider';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                       params: {locale},
                                   }: Readonly<{
    children: React.ReactNode;
    params: Params;
}>) {

    const fonts = classNames(nunito.className);
    return (
        <html lang='en'>
        <body className={fonts}>
        <TranslationProvider locale={locale}>
            <RootLayoutComponent>
                {children}
            </RootLayoutComponent>
        </TranslationProvider>

        </body>
        </html>
    );
}
